"""Kildene appen høster fra – ett oppslag per visningssted.

Hver kilde er en ordbok. Feltene som betyr noe:
    id            – stabil nøkkel, brukes i basen
    navn          – slik galleriet skal hete i appen
    kategori      – museum | kunsthall | galleri | kunstnerdrevet
    url           – nettstedets forside (vises i appen)
    sider         – oversiktssidene som skal hentes (uten: bruker url)
    element       – CSS-velger som rammer inn én utstilling
    tittel/dato/kunstnere/bilde/sammendrag/merkelapp – CSS-velgere i elementet
                    (flere alternativer skilles med |)
    hopp_over     – titler som ikke er utstillinger (regex)

Nye gallerier legges til ved å skrive en ny ordbok her. Test med:
    .venv/bin/python hent.py <id>
"""

REGIONER = {
    "oslo":       "Oslo og Østlandet",
    "sorlandet":  "Sørlandet",
    "vestlandet": "Bergen og Vestlandet",
    "midt":       "Trondheim og Midt-Norge",
    "nordland":   "Bodø og Nordland",
    "troms":      "Tromsø og Troms",
    "finnmark":   "Alta og Finnmark",
}

SAFARI = {"User-Agent": ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 "
                         "(KHTML, like Gecko) Version/17.4 Safari/605.1.15")}

KILDER: list[dict] = [
    # ───────────────────────── museer ─────────────────────────
    {
        "id": "nasjonalmuseet", "region": "oslo", "navn": "Nasjonalmuseet", "kategori": "museum",
        "url": "https://www.nasjonalmuseet.no/", "bydel": "Vika",
        "type_adapter": "funk", "funksjon": "nasjonalmuseet",
        "detalj_dato": ".event-metadata__text-and-icon span.block|.event-metadata__text-and-icon",
        "adresse": "Brynjulf Bulls plass 3, 0250 Oslo",
        "lat": 59.91163, "lon": 10.72842,
    },
    {
        "id": "nasjonalbiblioteket", "region": "oslo", "navn": "Nasjonalbiblioteket",
        "kategori": "museum", "bydel": "Solli plass",
        "url": "https://www.nb.no/",
        "adresse": "Henrik Ibsens gate 110, 0255 Oslo",
        "lat": 59.91470, "lon": 10.71640,
        "sider": ["https://www.nb.no/hva-skjer/"],
        "element": ".t2-featured-single-post",
        "tittel": ".wp-block-t2-post-title",
        "dato": ".nb-post-subtitle|.nb-post-read-more|.wp-block-t2-post-date",
        "merkelapp": ".nb-post-label",
        # /tv/ er strømmetjenesten deres, ikke noe som henger på veggen
        "url_monster": r"nb\.no/(utstilling|hva-skjer)/",
        "maks": 60,
    },
    {
        "id": "munch", "region": "oslo", "navn": "MUNCH", "kategori": "museum", "bydel": "Bjørvika",
        "url": "https://www.munch.no/", "sider": ["https://www.munch.no/utstillinger"],
        "hoder": SAFARI,
        "element": ".ExhibitionCard",
        "tittel": ".ExhibitionCard__subtitle|.ExhibitionCard__title",
        "kunstnere": ".ExhibitionCard__title",
        "dato": ".ExhibitionCard__intro span|.ExhibitionCard__intro",
        "url_monster": r"/utstillinger/",
        "reserve": True,          # munch.no stenger ute datasentre
        "adresse": "Edvard Munchs plass 1, 0194 Oslo",
        "lat": 59.90562, "lon": 10.75516,
    },
    {
        "id": "afmuseet", "region": "oslo", "navn": "Astrup Fearnley Museet", "kategori": "museum",
        "bydel": "Tjuvholmen", "url": "https://www.afmuseet.no/",
        "sider": ["https://www.afmuseet.no/utstillinger/", "https://www.afmuseet.no/arrangementer/"],
        "element": ".t2-featured-single-post",
        "tittel": ".wp-block-t2-post-title",
        "dato": ".wp-block-afm-block-post-dates",
        "merkelapp": ".wp-block-afm-block-post-type",
        "sammendrag": ".t2-post-excerpt",
        "adresse": "Strandpromenaden 2, 0252 Oslo",
        "lat": 59.90693, "lon": 10.72194,
    },
    {
        "id": "hok", "region": "oslo", "navn": "Henie Onstad Kunstsenter", "kategori": "museum",
        "bydel": "Høvikodden", "url": "https://www.hok.no/",
        "adresse": "Sonja Henies vei 31, 1311 Høvikodden",
        "lat": 59.88864, "lon": 10.55349,
        # /utstillinger er et arkiv med gamle utstillinger. Det som går nå
        # ligger under /program.
        "sider": ["https://www.hok.no/program"],
        "element": "article.grid-item",
        "tittel": "h3",
        "kunstnere": ".f-sm",
        "url_monster": r"/utstillinger/",
        # Oversikten har ingen datoer i det hele tatt – de står på hver
        # utstillingsside, i feltet over tittelen.
        "detalj": True,
        "detalj_dato": ".sticky span.block|.grid-wrap span.block|span.block",
    },
    {
        "id": "vigeland", "region": "oslo", "navn": "Vigeland-museet", "kategori": "museum",
        "bydel": "Frogner", "url": "https://vigeland.museum.no/",
        "element": "a[href*='/utstillinger/']", "lenke": "self",
        "tittel": "self",
        "dato": ".f-sm|time|.date",
        "url_monster": r"/utstillinger/[^/]+$",
        "detalj": True, "tittel_fra_detalj": True, "krev_dato": True,
        "adresse": "Nobels gate 32, 0268 Oslo",
        "lat": 59.92312, "lon": 10.70185,
    },

    # ─────────────────────── kunsthaller ───────────────────────
    {
        "id": "kunstnerneshus", "region": "oslo", "navn": "Kunstnernes Hus", "kategori": "kunsthall",
        "bydel": "St. Hanshaugen", "url": "https://kunstnerneshus.no/",
        "sider": ["https://kunstnerneshus.no/program"],
        "element": "article.LinkItem",
        "tittel": "h1",
        "kunstnere": ".LinkItem__head__sub",
        "dato": ".LinkItem__head__sub",
        "merkelapp": ".LinkItem__head__categories",
        "adresse": "Wergelandsveien 17, 0167 Oslo",
        "lat": 59.91954, "lon": 10.73079,
    },
    {
        "id": "kunsthalloslo", "region": "oslo", "navn": "Kunsthall Oslo", "kategori": "kunsthall",
        "bydel": "Bjørvika", "url": "https://kunsthalloslo.no/",
        "sider": ["https://kunsthalloslo.no/?lang=nb"],
        "element": "li.wp-block-post",
        "tittel": ".wp-block-post-title",
        "dato": ".wp-block-post-excerpt|.wp-block-post-date|time",
        "sammendrag": ".wp-block-post-excerpt",
        "adresse": "Rostockgata 2, 0191 Oslo",
        "lat": 59.90796, "lon": 10.76152,
    },
    {
        "id": "uks", "region": "oslo", "navn": "UKS – Unge Kunstneres Samfund", "kategori": "kunsthall",
        "bydel": "Grønland", "url": "https://www.uks.no/",
        "element": "section.section__hero .row",
        "tittel": ".column__title",
        "dato": ".column__date|.column--two|.column",
        "kunstnere": ".column__artists|.column__subtitle",
        "adresse": "Keysers gate 1, 0165 Oslo",
        "lat": 59.91705, "lon": 10.74385,
        "detalj": True,           # oversikten har ingen bilder
    },
    {
        "id": "oslokunstforening", "region": "oslo", "navn": "Oslo Kunstforening", "kategori": "kunsthall",
        "bydel": "Kvadraturen", "url": "https://www.oslokunstforening.no/",
        "element": "li.archive__item",
        "tittel": ".archive__item__title em|.archive__item__title",
        "kunstnere": ".archive__item__title",
        "dato": ".small",
        "ar_hint": {"foreldre": ".rows", "velger": ""},
        "url_monster": r"/utstillinger/",
        "maks": 80,
        "adresse": "Rådhusgata 19, 0158 Oslo",
        "lat": 59.91014, "lon": 10.74033,
    },
    {
        "id": "fotogalleriet", "region": "oslo", "navn": "Fotogalleriet", "kategori": "kunsthall",
        "bydel": "Sentrum", "url": "https://fotogalleriet.no/",
        "element": "li.grid-item.exhibition, li.grid-item.event",
        "tittel": ".content-title",
        "kunstnere": ".content-inner--title .content-subtitle",
        "dato": ".exhibition-dates|.content-date",
        "merkelapp": ".content-inner--info .content-subtitle",
        "adresse": "Møllergata 34, 0179 Oslo",
        "lat": 59.91746, "lon": 10.75026,
    },
    {
        "id": "kunstnerforbundet", "region": "oslo", "navn": "Kunstnerforbundet", "kategori": "kunsthall",
        "bydel": "Kvadraturen", "url": "https://kunstnerforbundet.no/",
        "sider": ["https://kunstnerforbundet.no/utstillinger"],
        "element": ".periods article",
        "underelement": ".exhibition",
        "tittel": "a",
        "dato": ".period",
        "url_monster": r"/utstillinger/",
        "detalj": True, "maks": 60,
        "adresse": "Kjeld Stubs gate 3, 0160 Oslo",
        "lat": 59.91286, "lon": 10.73561,
    },

    # ──────────────── kommersielle gallerier ────────────────
    {
        "id": "standardoslo", "region": "oslo", "navn": "STANDARD (OSLO)", "kategori": "galleri",
        "bydel": "Bislett", "url": "https://www.standardoslo.no/",
        "sider": ["https://www.standardoslo.no/exhibitions"],
        "element": "ul.clearwithin > li",
        "tittel": ".title|h2|h3",
        "dato": ".date|.dates|.caption",
        "url_monster": r"/exhibitions/",
        "krev_dato": True,
        "adresse": "Eilert Sundts gate 40, 0355 Oslo",
        "lat": 59.92328, "lon": 10.72051,
    },
    {
        "id": "oslcontemporary", "region": "oslo", "navn": "OSL contemporary", "kategori": "galleri",
        "bydel": "Skøyen", "url": "https://oslcontemporary.com/",
        "sider": ["https://oslcontemporary.com/exhibitions"],
        "element": ".opener-preview",
        "tittel": ".inner-col p|h3",
        "kunstnere": "h3",
        "dato": "p.label",
        "ar_hint": {"foreldre": "section.waypoint", "velger": "h2|h3|.year"},
        "url_monster": r"/exhibitions/",
        "krev_dato": True,
        "adresse": "Haxthausens gate 3, 0263 Oslo",
        "lat": 59.91725, "lon": 10.714,
    },
    {
        "id": "galleririis", "region": "oslo", "navn": "Galleri Riis", "kategori": "galleri",
        "bydel": "Frogner", "url": "https://galleririis.com/",
        "sider": ["https://galleririis.com/exhibitions"],
        "element": "a.exhibition", "lenke": "self",
        "tittel": ".exhibition-name",
        "kunstnere": ".exhibition-artists",
        "dato": ".info div",
        "krev_dato": True, "maks": 40,
        "adresse": "Arbins gate 7, 0253 Oslo",
        "lat": 59.91454, "lon": 10.72648,
    },
    {
        "id": "semmingsen", "region": "oslo", "navn": "Galleri Semmingsen", "kategori": "galleri",
        "bydel": "Frogner", "url": "https://semmingsen.no/",
        "element": ".ue-grid-item",
        "tittel": ".ue-grid-item-title",
        "dato": ".ue-grid-item-title",
        "krev_dato": True, "maks": 20,
        "adresse": "Niels Juels gate 50, 0257 Oslo",
        "lat": 59.91754, "lon": 10.71517,
        "reserve": True,      # svarer tomt til datasentre
    },
    {
        "id": "format", "region": "oslo", "navn": "Galleri Format", "kategori": "galleri",
        "bydel": "Sentrum", "url": "https://www.format.no/",
        "sider": ["https://www.format.no/exhibitions-1", "https://www.format.no/upcoming"],
        "element": ".sqs-block.image-block",
        "tittel": "self",
        "dato": ".image-subtitle|p|self",
        "krev_dato": True, "maks": 30,
        "adresse": "Rådhusgata 24, 0151 Oslo",
        "lat": 59.90961, "lon": 10.74169,
    },

    # ──────────────── kunstnerdrevne og andre ────────────────
    {
        "id": "femtensesse", "region": "oslo", "navn": "FEMTENSESSE", "kategori": "kunstnerdrevet",
        "bydel": "Ryen", "url": "https://femtensesse.no/",
        "element": "article.query-item.item-s-12",
        "tittel": "h2|h3|.query-item-title",
        "kunstnere": "h3|.query-item-subtitle",
        "dato": ".query-item-date|p|div",
        "url_monster": r"femtensesse\.no/(project|exhibition)",
        "krev_dato": True, "maks": 30,
        "adresse": "Bjørn Stallares vei 21, 0574 Oslo",
        "lat": 59.93278, "lon": 10.78126,
    },
    {
        "id": "ateliernord", "region": "oslo", "navn": "Atelier Nord", "kategori": "kunstnerdrevet",
        "bydel": "Grünerløkka", "url": "https://ateliernord.no/",
        "element": "article, .main-project-title-container",
        "tittel": "h2.entry-title|h2|h3",
        "dato": "time|.date",
        "url_monster": r"ateliernord\.no/(?!$|\?|#)[a-z0-9-]{4,}",
        # utlysninger er ikke utstillinger, og datoene i teksten er søknadsfrister
        "hopp_over": [r"open call", r"utlysning", r"residency"],
        "detalj": True, "krev_dato": True, "maks": 20,
        "adresse": "Olaf Ryes plass 2, 0552 Oslo",
        "lat": 59.92227, "lon": 10.75819,
        "reserve": True,      # svarer tomt til datasentre
    },
    {
        "id": "norskegrafikere", "region": "oslo", "navn": "Norske Grafikere", "kategori": "galleri",
        "bydel": "Sentrum", "url": "https://norske-grafikere.no/",
        "sider": ["https://norske-grafikere.no/utstillinger/",
                  "https://norske-grafikere.no/tidligere-utstillinger/"],
        "element": "figcaption.rollover-content",
        "tittel": ".entry-title",
        "dato": "p",
        "sammendrag": "p:nth-of-type(2)",
        "krev_dato": True, "maks": 40,
        "adresse": "Tollbugata 24, 0157 Oslo",
        "lat": 59.91091, "lon": 10.74174,
    },
    {
        "id": "lnm", "region": "oslo", "navn": "Galleri LNM", "kategori": "galleri",
        "bydel": "Sentrum", "url": "https://lnm.no/",
        "sider": ["https://lnm.no/utstillinger"],
        "element": "div.col.three",
        "tittel": "h3",
        "kunstnere": "h2",
        "dato": "figcaption .body-size",
        "url_monster": r"/utstillinger/",
        "maks": 60,
        "adresse": "Rådhusgata 37, 0158 Oslo",
        "lat": 59.91083, "lon": 10.7368,
    },
    # ───────────────────────── Sørlandet ─────────────────────────
    {
        "id": "kunstsilo", "region": "sorlandet", "navn": "Kunstsilo", "kategori": "museum",
        "bydel": "Kristiansand", "url": "https://www.kunstsilo.no/",
        "adresse": "Sjølystveien 8, 4610 Kristiansand",
        "lat": 58.13821, "lon": 7.99715,
        "sider": ["https://www.kunstsilo.no/no/utstillinger"],
        "element": "a.slide", "lenke": "self",
        "tittel": "h3",
        "kunstnere": ".tag",
        "url_monster": r"/utstillinger/",
        # Kunstsilo oppgir ingen datoer, verken i listen eller på sidene.
        "maks": 30,
    },
    {
        "id": "bomuldsfabriken", "region": "sorlandet", "navn": "Bomuldsfabriken Kunsthall",
        "kategori": "kunsthall", "bydel": "Arendal",
        "url": "https://bomuldsfabriken.no/",
        "adresse": "Oddenveien 5, 4836 Arendal",
        "lat": 58.46825, "lon": 8.75152,
        "sider": ["https://bomuldsfabriken.no/utstillinger/"],
        "element": ".kunst-archive-item",
        "tittel": "h2|h3",
        "dato": ".kunst-meta-info|.kunst-meta",
        "merkelapp": ".bubble-text",
        "maks": 25,
    },
    {
        "id": "kristiansandkunsthall", "region": "sorlandet", "navn": "Kristiansand Kunsthall",
        "kategori": "kunsthall", "bydel": "Kristiansand",
        "url": "https://www.kristiansandkunsthall.no/",
        "adresse": "Rådhusgata 11, 4611 Kristiansand",
        "lat": 58.14564, "lon": 7.99418,
        "element": ".home-list-block, article",
        "tittel": "h2|h3|.title",
        "dato": "time|.date|p",
        "detalj": True, "krev_dato": True, "maks": 20,
    },

    # ──────────────────── Bergen og Vestlandet ────────────────────
    {
        "id": "bergenkunsthall", "region": "vestlandet", "navn": "Bergen Kunsthall",
        "kategori": "kunsthall", "bydel": "Bergen",
        "url": "https://www.kunsthall.no/",
        "adresse": "Rasmus Meyers allé 5, 5015 Bergen",
        "lat": 60.38976, "lon": 5.32654,
        "sider": ["https://www.kunsthall.no/no/"],
        "element": ".khb-card",
        "tittel": ".khb-card-title|.uk-h4",
        "kunstnere": ".uk-h4",
        # Datoene står som to <time> ved siden av hverandre; teksten rundt dem
        # har begge, og lar seg lese som en periode.
        "dato": ".khb-card-text|.uk-card-body",
        "merkelapp": ".uk-label|.khb-card-label",
        "maks": 40,
    },
    {
        "id": "kode", "region": "vestlandet", "navn": "KODE", "kategori": "museum",
        "bydel": "Bergen", "url": "https://www.kodebergen.no/",
        "adresse": "Rasmus Meyers allé 9, 5015 Bergen",
        "lat": 60.38929, "lon": 5.32894,
        "sider": ["https://www.kodebergen.no/hva-skjer/utstillinger"],
        "element": "a[href*='/hva-skjer/utstillinger/']", "lenke": "self",
        "tittel": "h4|h3",
        "kunstnere": "h3",
        "url_monster": r"/hva-skjer/utstillinger/.+",
        "detalj": True, "detalj_dato": "time|[class*='EventHeader_infoContent']",
        "krev_dato": True, "maks": 30,
    },
    {
        "id": "kunsthallstavanger", "region": "vestlandet", "navn": "Kunsthall Stavanger",
        "kategori": "kunsthall", "bydel": "Stavanger",
        "url": "https://kunsthallstavanger.no/",
        "adresse": "Madlaveien 33, 4009 Stavanger",
        "lat": 58.96275, "lon": 5.72239,
        "element": "li.Calendar-programItem",
        "tittel": ".Calendar-programTitle",
        "dato": ".Calendar-programMeta",
        "merkelapp": ".Calendar-programType",
        "detalj": True,          # oversikten har ingen bilder
        "maks": 30,
    },

    # ─────────────────── Trondheim og Midt-Norge ───────────────────
    {
        "id": "kunsthalltrondheim", "region": "midt", "navn": "Kunsthall Trondheim",
        "kategori": "kunsthall", "bydel": "Trondheim",
        "url": "https://kunsthalltrondheim.no/",
        "adresse": "Kongens gate 2, 7011 Trondheim",
        "lat": 63.43046, "lon": 10.40056,
        "element": "section.entry-exhibition",
        # Kunstner og tittel ligger som to spann etter hverandre.
        "tittel": "[class*='pull-4'] span span:nth-of-type(2)|[class*='pull-4']",
        "kunstnere": "[class*='pull-4'] span span:nth-of-type(1)",
        "dato": ".datetime-block|time",
        "merkelapp": "[class*='section-subti'] span:nth-of-type(1)",
        "detalj": True,          # oversikten har ingen bilder
        "maks": 25,
    },
    {
        "id": "trondheimkunstmuseum", "region": "midt", "navn": "Trondheim kunstmuseum",
        "kategori": "museum", "bydel": "Trondheim",
        "url": "https://trondheimkunstmuseum.no/",
        "adresse": "Bispegata 7B, 7013 Trondheim",
        "lat": 63.42741, "lon": 10.39451,
        "sider": ["https://trondheimkunstmuseum.no/utstillinger"],
        "element": ".module--card",
        "tittel": "h3.card-title|h3|h2",
        "dato": ".meta--date|time",
        "kunstnere": ".meta--location",
        "maks": 25,
    },
    {
        "id": "tssk", "region": "midt", "navn": "Trøndelag senter for samtidskunst",
        "kategori": "kunsthall", "bydel": "Trondheim",
        "url": "https://samtidskunst.no/",
        "adresse": "Fjordgata 11, 7010 Trondheim",
        "lat": 63.4346, "lon": 10.40141,
        "element": "a[href*='/event/'], a[href*='/utstilling/']", "lenke": "self",
        "tittel": "h2|h3|self",
        "dato": "h4|self",
        "detalj": True, "krev_dato": True, "maks": 25,
    },

    # ───────────────────── Tromsø og Troms ─────────────────────
    {
        "id": "nnkm", "region": "troms", "navn": "Nordnorsk Kunstmuseum",
        "kategori": "museum", "bydel": "Tromsø",
        "url": "https://nnkm.no/",
        "adresse": "Sjøgata 1, 9008 Tromsø",
        "lat": 69.64826, "lon": 18.9596,
        "sider": ["https://nnkm.no/utstillinger"],
        "element": "[class*='col-start-4']",
        "tittel": "[class*='order-2']",
        "kunstnere": "[class*='w-1/4']",
        "dato": "[class*='w-3/4']",
        "krev_dato": True, "maks": 40,
        "detalj": True,          # oversikten har ingen bilder
    },
    {
        "id": "tromsokunstforening", "region": "troms", "navn": "Tromsø Kunstforening",
        "kategori": "kunsthall", "bydel": "Tromsø",
        "url": "https://www.tromsokunstforening.no/",
        "adresse": "Muségata 2, 9008 Tromsø",
        "lat": 69.64551, "lon": 18.94724,
        "sider": ["https://www.tromsokunstforening.no/no/exhibitions",
                  "https://www.tromsokunstforening.no/no/events"],
        "element": "a[href*='/exhibitions/'], a[href*='/events/']", "lenke": "self",
        "tittel": "h2|h3|self",
        "dato": "self",
        "url_monster": r"/(exhibitions|events)/.+",
        "detalj": True, "krev_dato": True, "maks": 25,
    },

    # ───────────────────── Alta og Finnmark ─────────────────────
    {
        "id": "pikene", "region": "finnmark", "navn": "Pikene på Broen",
        "kategori": "kunstnerdrevet", "bydel": "Kirkenes",
        "url": "https://www.pikene.no/",
        "adresse": "Kirkegata 2, 9900 Kirkenes",
        "lat": 69.72796, "lon": 30.04091,
        "element": ".esg-entry-cover, article",
        "tittel": "h2|h3|.eg-post-title",
        "dato": "time|.date|p",
        "detalj": True, "krev_dato": True, "maks": 20,
    },
    # ──────────────── Østlandet utenfor Oslo ────────────────
    {
        "id": "gallerif15", "region": "oslo", "navn": "Galleri F 15", "kategori": "kunsthall",
        "bydel": "Moss", "url": "https://gallerif15.no/",
        "adresse": "Albyalleen 60, 1519 Moss",
        "sider": ["https://gallerif15.no/exhibitions_f15/",
                  "https://gallerif15.no/exhibitions_momentum/"],
        "element": "a[href*='/exhibitions_']", "lenke": "self",
        "tittel": "h2|h3|self",
        "dato": "self",
        "url_monster": r"/exhibitions_[a-z0-9]+/[a-z0-9][a-z0-9-]{3,}/?$",
        "detalj": True, "detalj_dato": ".is-date|time", "krev_dato": True, "maks": 25,
    },
    {
        "id": "kunsthallgrenland", "region": "oslo", "navn": "Kunsthall Grenland",
        "kategori": "kunsthall", "bydel": "Porsgrunn",
        "url": "https://kunsthallgrenland.no/",
        "adresse": "Ælvespeilet, Kverndalsgata 8, 3717 Skien",
        "element": ".wp-block-column",
        "tittel": "h2|h3|.wp-block-heading",
        "dato": "time|p|self",
        "url_monster": r"kunsthallgrenland\.no/[a-z0-9-]{5,}",
        "krev_dato": True, "maks": 20,
    },
    {
        "id": "kistefos", "region": "oslo", "navn": "Kistefos", "kategori": "museum",
        "bydel": "Jevnaker", "url": "https://www.kistefosmuseum.com/",
        "adresse": "Samsmoveien 41, 3520 Jevnaker",
        "element": "article, .card, li",
        "tittel": "h2|h3|.title",
        "dato": "time|.date|p",
        "url_monster": r"kistefosmuseum\.com/[a-z0-9-]{5,}",
        "detalj": True, "krev_dato": True, "maks": 20,
    },
    {
        "id": "ostfoldkunstsenter", "region": "oslo", "navn": "Østfold kunstsenter",
        "kategori": "kunsthall", "bydel": "Fredrikstad",
        "url": "https://www.ostfold-kunstsenter.no/",
        "adresse": "Tollbodgaten 105, 1632 Gamle Fredrikstad",
        "element": "article, .card, li",
        "tittel": "h2|h3|.entry-title",
        "dato": "time|.date|p",
        "detalj": True, "krev_dato": True, "maks": 20,
    },
    {
        "id": "detgulehuset", "region": "oslo", "navn": "Det Gule Huset", "kategori": "galleri",
        "bydel": "Fredrikstad", "url": "https://www.detgulehuset.no/",
        "sider": ["https://www.detgulehuset.no/utstillinger-1"],
        "element": "a[href], article", "lenke": "self",
        "tittel": "h2|h3|self",
        "dato": "time|.date|self",
        "url_monster": r"detgulehuset\.no/[a-z0-9-]{5,}",
        "detalj": True, "krev_dato": True, "maks": 20,
    },

    # ──────────────── Midt-Norge, ny kilde ────────────────
    {
        "id": "kuk", "region": "midt", "navn": "K.U.K – Kjøpmannsgata Ung Kunst",
        "kategori": "kunsthall", "bydel": "Trondheim",
        "url": "https://www.k-u-k.no/",
        "adresse": "Kjøpmannsgata 46, 7010 Trondheim",
        "sider": ["https://www.k-u-k.no/utstillinger/"],
        "element": ".et_pb_blurb, .et_pb_text, article",
        "tittel": "h2.et_pb_module_header|h2|h3|h4",
        "dato": "self|p",
        "url_monster": r"k-u-k\.no/project/",
        "detalj": True,
        "maks": 20,
    },
]


KILDE_ETTER_ID = {k["id"]: k for k in KILDER}
